# Generated by Django 3.2 on 2021-05-02 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Formulaire', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='gyclémie_2',
        ),
        migrations.AlterField(
            model_name='patient',
            name='date_creation',
            field=models.DateField(auto_now=True, null=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='date_naissance',
            field=models.DateField(blank=True, null=True, verbose_name='Date de naissance'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gyclémie_1',
            field=models.FloatField(blank=True, null=True, verbose_name='Glycémie (mmol/L)'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='interpretation_imc',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Interprétation IMC'),
        ),
    ]
