# Generated by Django 3.2 on 2021-05-02 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Formulaire', '0003_auto_20210502_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='date_creation_str',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Date de creation'),
        ),
        migrations.AddField(
            model_name='patient',
            name='date_naissance_str',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Date de naissance'),
        ),
    ]
